# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the auto correlation time
#' from \url{https://github.com/beast-dev/beast-mcmc/blob/800817772033c13061f026226e41128d21fd14f3/src/dr/inference/trace/TraceCorrelation.java#L159} # nolint
#' @param sample sample
#' @param sample_interval sample interval
#' @return the auto correlation time
#' @author Richèl J.C. Bilderbeek
calc_act_cpp <- function(sample, sample_interval) {
    .Call('_tracerer_calc_act_cpp', PACKAGE = 'tracerer', sample, sample_interval)
}

#' Calculates the standard error of the mean
#' @param sample numeric vector of values
#' @return the standard error of the mean
#' @author Richèl J.C. Bilderbeek
calc_std_error_of_mean_cpp <- function(sample) {
    .Call('_tracerer_calc_std_error_of_mean_cpp', PACKAGE = 'tracerer', sample)
}

